#!/usr/bin/env php
<?php
// require_once __DIR__ . '/vendor/autoload.php';
// if (
//     (!$classLoader = file_exists(__DIR__ . '/vendor/autoload.php')) &&
//     (!$classLoader = file_exists(__DIR__ . '/../../autoload.php'))
// ) {
//     echo 'You must set up the project dependencies, run the following commands:' . PHP_EOL .
//         'curl -sS https://getcomposer.org/installer | php' . PHP_EOL .
//         'php composer.phar install' . PHP_EOL;
//     exit(1);
// }

if (file_exists(__DIR__ . '/../../autoload.php')) {
    require __DIR__ . '/../../autoload.php';
} else {
    require __DIR__ . '/vendor/autoload.php';
}

require_once __DIR__ . '\src\Register\register.php';

exit();
